version: 2.1

orbs:
  discord: antonioned/discord@0.1.0

jobs:
  build-and-test:
    docker:
    - image: cimg/node:16.14.0
    steps:
    - checkout
    - run:
        name: print random text
        command: echo "HELLO"
    - discord/status:
        fail_only: false
        success_message: "**${CIRCLE_USERNAME}**'s with email: romanplatonov@icloud.com, pipeline id is << pipeline.id >> , build: **${CIRCLE_BUILD_URL}** succeeded"
        webhook: "${DISCORD_WEBHOOK_URL}"


workflows:
  run-tests:
    jobs:
    - build-and-test
